spothero/UtilityBelt-iOS

.github/CODEOWNERS, .gitignore, .swiftformat, .swiftlint.yml, .zinc/rubocop.yml
- Ran `mint run zinc`, fixed `.swiftlint.yml` file to include `missing_docs` still.
=> Updated with Zinc

Sources/UtilityBeltNetworking/Enums/ParameterEncoding.swift, UtilityBelt.podspec
Needed this method to be public for upcoming `SpotHeroAPI` changes. It was a mistake that it was internal.
=> Made defaultEncoding(for:) public

Sources/UtilityBeltNetworking/Extensions/URLRequest+HTTPHeader.swift, Sources/UtilityBeltNetworking/Extensions/URLRequest+SetHeaders.swift, Sources/UtilityBeltNetworking/HTTPClient.swift, Sources/UtilityBeltNetworking/Protocols/HTTPHeaderConvertible.swift, Sources/UtilityBeltNetworking/Protocols/HTTPHeaderDictionaryConvertible.swift, Sources/UtilityBeltNetworking/Protocols/URLConvertible.swift, Sources/UtilityBeltNetworking/Protocols/URLRequestConvertible.swift
**JIRA URL**
https://spothero.atlassian.net/browse/IOS-1940
- Added `URLRequest+SetHeaders` extension method for adding a single header via the `HTTPHeader` enum or a dictionary headers.
- Added the `HTTPHeaderConvertible` for allowing easy passing of `String` and `HTTPHeader` types.
- Added the `HTTPHeaderDictionaryConvertible` for allowing singular `HTTPClient.request` methods to accept HTTP header dictionaries of any type. Also allows downstream consumers to implement their own `HTTPHeaderDictionaryConvertible` structs if they so desire.
- I haven't yet decided how I want to implement the `JSONDecoder` that can be passed into the `HTTPClient`, so for now I'm just passing it along with the request. I added a [ticket](https://spothero.atlassian.net/browse/IOS-1958) for …
=> IOS-1940: Implemented headers in HTTPClient.request methods

Sources/UtilityBeltNetworking/Enums/UBNetworkError.swift, Sources/UtilityBeltNetworking/Extensions/CharacterSet+RFC3986Unreserved.swift, Sources/UtilityBeltNetworking/Extensions/URLComponents+SetQueryItems.swift, Sources/UtilityBeltNetworking/HTTPClient.swift, UtilityBelt.podspec
- Added `CharacterSet+RFC3986Unreserved` extension to improve processing of URL encoded parameters.
- Added `Data` type checking to avoid decoding `Data` when it isn't necessary.
=> Added RFC3986 encoding to HTTPClient

Sources/Sham/Models/StubRequest.swift, Tests/ShamTests/Tests/StubRequestTests.swift, UtilityBelt.podspec
**JIRA URL**
https://spothero.atlassian.net/browse/IOS-1355
- Added ability for stubbed requests to validate based on query string parameters regardless of the order they are being requested.
- Inverted validation checks in `StubRequest.canMockData` for optimization.
=> IOS-1355: Added stub query string comparison that ignores sort order

README.md, Tests/UtilityBeltNetworkingTests/Tests/ParameterEncodingTests.swift, UtilityBelt.xcworkspace/xcshareddata/xcschemes/UtilityBelt.xcscheme, Zincfile
- Deleted the `pull_request_template.md` from this library and removed it from Zincfile. We'll rely on the Organization's [default community health file repository](http://github.com/spothero/.github) while it aligns.
- Updated README to include a notice of the state of the repository.
=> Added open-source notice to README

Sources/UtilityBeltKeychain/Models/Keychain.swift, Sources/UtilityBeltNetworking/Extensions/Dictionary+AsJSONSerializedData.swift, Tests/UtilityBeltNetworkingTests/Tests/ParameterEncodingTests.swift
- Added `tvOS 11.3` to the usage of `SecCopyErrorMessageString`.
- Added `tvOS 11.0` to usage of `.sortedKeys` in the `dataInBody(request:)` method.
- Updated usage of `.sortedKeys` to reduce repetition of code.
=> Updated files for platform version compatability

.github/pull_request_template.md
Deleting this file will fall back on using the SpotHero GitHub Community Health Files, which we want to be using for all OSS projects.
=> Deleted custom pull_request_template.md

Sources/Sham/MockService.swift, Sources/Sham/Models/StubRequest.swift, Tests/ShamTests/Tests/MockServiceTests.swift
- removes os logging and replaces it with configurable print calls
- removes previous hashable implementation that didnt handle base URLs well
- creates a simple priority function that will prioritize the best matching stubbed request for incoming requests
=> Add a prioritization score to match incoming requests

Tests/UtilityBeltDataTests/Protocols/CoreDataOperatorTesting.swift, Tests/UtilityBeltDataTests/Tests/CoreData/CoreDataOperatorInMemoryTests.swift, Tests/UtilityBeltDataTests/Tests/CoreData/CoreDataOperatorSQLiteTests.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-1930
Adding test coverage for:
- Individual entity fetch requests 
- Individual entity fetch requests with predicate
- Multiple entity fetch requests
- Multiple entity fetch requests with predicate
- Multiple entity fetch requests with sort descriptors 
- Multiple entity fetch requests with fetch limits
=> IOS-1930: feature/add CoreData fetch request test coverage

Sources/UtilityBeltNetworking/Extensions/Encodable+AsDictionary.swift, Sources/UtilityBeltNetworking/Extensions/URLRequest+SetParameters.swift, Sources/UtilityBeltNetworking/HTTPClient+Combine.swift, Sources/UtilityBeltNetworking/HTTPClient.swift, Sources/UtilityBeltNetworking/Protocols/ParameterDictionaryConvertible.swift
**Issue Link**
IOS-1943
This PR updates our `HTTPClient` to allow conformance to `ParameterConvertible` and adds convenience methods for passing `Encodable` types by default.
I can't think of a clean way of doing `extension Encodable: ParameterConvertible { ... }` (which doesn't work, but if anyone has a better idea I'm open to it! Would love to not have the convenience methods.
Also updated a bunch of documentation.
=> IOS-1943: Updated for Encodable and ParameterConvertible support

Sources/UtilityBeltNetworking/HTTPClient.swift, Tests/UtilityBeltNetworkingTests/Tests/HTTPClientTests.swift
**Issue Link**
IOS-1969
Adds a `timeoutInterval` property on the HTTPClient.
=> IOS-1969: Feature/Add timeout property to HTTPClient

Sources/UtilityBeltData/CoreData/CoreDataOperator.swift
**JIRA Ticket**
https://spothero.atlassian.net/browse/IOS-2591
Discovered an issue where we were performing a save and merge operation all on the same queue - the child Managed Object Context's private background queue.
Because the main context is a main queue MOC and Core Data MOCs are not thread safe, this will lead to a crash.
I've updated this to ensure the main context operations are perform on its own queue by using the `perform` block to do the save.
=> IOS-2591: bugfix/threading issues on save and merge

Sources/UtilityBeltUITesting/Models/CoreDataConfiguration.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-2695
Added a configuration object that allows the passing of a database URL into the main app target.
=> IOS-2695: Feature/Core Data Config for XCUITesting

Package.swift, Sources/UtilityBeltUITesting/Extensions/UserDefaultsConfiguration+UserDefaults.swift, Sources/UtilityBeltUITesting/Models/UserDefaultsConfiguration.swift, Sources/UtilityBeltUITesting/Models/UserDefaultsObject.swift, Tests/UtilityBeltUITestingTests/Tests/UserDefaultsConfigurationTests.swift, Tests/UtilityBeltUITestingTests/Tests/UserDefaultsObjectTests.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-2697
Added a configuration object to store UserDefaults data to be injected in the main app when UI testing.
The configuration object has two properties, `var standard: [UserDefaultsObject]` and `customSuites: [String: [UserDefaultsObject]]`. The former contains objects to be injected into `UserDefaults.standard` and the later contains array of objects to be injected into UserDefaults with custom suite names, represented by the dictionary's key.
The `UserDefaultsObject`s have two properties, `key` and `value`. The former is the string key used in UserDefaults. The latter is a `Codable` type for easy transfer to the main app, with support for basic types which can be stored in UserDefaults.
=> IOS-2697: Feature/UserDefaults XCUI Injection

Sources/UtilityBeltUITesting/Enumerations/LaunchArgument.swift, Sources/UtilityBeltUITesting/Extensions/ProcessInfo+LaunchArguments.swift, Sources/UtilityBeltUITesting_XCTestSupport/Extensions/XCUIApplication+LaunchArguments.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-2705
Creates a `LaunchArgument` enumeration.
Creates helper extensions for setting values from a test target and checking `LaunchArgument` values when running a test.
=> IOS-2705: Feature/Launch argument enumeration

Sources/UtilityBeltNetworking/Extensions/NSNumber+Boolean.swift, Sources/UtilityBeltNetworking/Extensions/URLComponents+SetQueryItems.swift, Tests/UtilityBeltNetworkingTests/Tests/NSNumberExtensionTests.swift, Tests/UtilityBeltNetworkingTests/Tests/ParameterEncodingTests.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-2791
When parameters are encoded using a `JSONSerialization` object, all the numbers become `NSNumber`s.
`NSNumber`s can be converted to `Bool`s, so the switch originally was formatting all number values from the serializer as boolean "true"/"false" strings.
This PR updates the evaluation of query parameters to properly distinguish between Swift booleans and integers, and `NSNumber` booleans and integers.
=> IOS-2791: Bugfix/Handle NSNumbers properly

Sources/UtilityBeltData/CoreData/CoreDataOperator.swift, UtilityBelt.xcworkspace/xcshareddata/xcschemes/UtilityBelt.xcscheme
SPM doesn't allow referencing a given package's Bundle outside of the package. Within the package, `Bundle.module` references the module's bundle (similar to `Bundle.main` from within an app or framework target). Instead, the pattern intended by SPM is to expose the resources you need via the API of the package itself, which is how `CoreDataHelper.modelURL` works.
This change allows an entrypoint into the method that doesn't handle the Bundle fetching itself without requiring any deprecations, but eventually we may want to move the other method (with `Bundle = .main`) entirely.
=> Updated initializeCoreDataStack to include signature without Bundle

Sources/Sham/Extensions/StubbedDataCollection+URLRequestConvertible.swift, Sources/Sham/MockService.swift, Sources/Sham/Models/StubbedDataCollection.swift, Sources/Sham/Protocols/MockURLProtocol.swift, Sources/Sham_XCTestSupport/Extensions/XCTestCase+Stub.swift, Sources/UtilityBeltUITesting/Extensions/MockService+LaunchEnvironment.swift, Tests/ShamTests/Tests/MockServiceTests.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-2691
Removes the thin wrapper functions in `MockService` that manipulate the stubbed data collection object and allows the direct manipulation of the `MockService.shared.stubbedDataCollection` property.
=> IOS-2691: Feature/Remove stub managing functions from the MockService class

Sources/UtilityBeltNetworking/HTTPClient.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-2589
Updated the `isDebugLoggingEnabled` flag so that it can be controlled at runtime vs compile time. Additionally, since the `DEBUG` flag is pretty common in iOS projects, it may be harder for projects that rely on it for other things to control UtilityBelt logging more granularly.
=> IOS-2589: Feature/Allow more flexible logging controls

Sources/UtilityBeltUITesting/Models/AnimationConfiguration.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-2916
Added a new property to `AnimationConfiguration` that allows passing information to the app target about the desired speed for the key window's layer.
=> IOS-2916: Feature/Control XCUI Layer Speed

.github/workflows/ci.yml
**Issue Link**
N/A
Fixes the failing Git Actions by allowing Danger to write to PRs.
=> Fix failing Git Actions

Sources/Sham/Models/StubResponse.swift, Sources/Sham/Protocols/MockURLProtocol.swift, Sources/UtilityBeltNetworking/Enums/UBNetworkError.swift, Sources/UtilityBeltNetworking/HTTPClient+Combine.swift, Sources/UtilityBeltNetworking/HTTPClient.swift, Sources/UtilityBeltNetworking/Models/MimeType.swift, Sources/UtilityBeltNetworking/Models/ResponseValidator.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-1967
This is marked with proposal because I just wanted to get some feedback on the solutions here.  If we are simply checking the content type is `application/json` in the response handler, I think just uncommenting the existing code is fine for the non-combine request builders.  Are we trying to do more here, like match content types against any Accept headers if they are there?
Also, for implementing this on the combine version, I think we have a couple options.  
1) expose the full `URLSession.DataTaskPublisher.Output` down the chain
2) pass in some kind of validation to the base call site.  I wrote up a very quick example of what this could look like.
option 1 feels like better use of combine, but I think option …
=> IOS-1967: Handle mime type check in decodable requests

Sources/Sham/Models/StubRequest.swift, Tests/ShamTests/Tests/StubRequestTests.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-1428
- Adds case insensitivity to matching URL paths.
=> IOS-1428: Add case insensitivity to matching URL paths

Sources/UtilityBeltNetworking/HTTPClient.swift, Sources/UtilityBeltNetworking/Models/Request.swift, Sources/UtilityBeltNetworking/Protocols/RequestAdapter.swift, Sources/UtilityBeltNetworking/Protocols/RequestInterceptor.swift, Tests/UtilityBeltNetworkingTests/Tests/RequestAdapterTests.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-3202
This is the first half of changes that will eventually allow for the ability to handle tasks such as renewing access tokens upon receiving a 401 from the server and retying a request with a refreshed access token before failing completely.
To achieve this, I'm planning the following:
- Create a `RequestAdapter` protocol which will allow clients to make changes to a request before it is sent to the server (e.x. add an `Authorization` header to the request with the proper credentials)
- Create a `RequestRetrier` protocol which will allow clients to see why a request failed and tell the HTTPClient whether or not it should retry to request (e.x. If the status code was 401, try renewing our access token and storing …
=> IOS-3202: Feature/Adapting URL Requests

Sources/UtilityBeltNetworking/HTTPClient.swift, Sources/UtilityBeltNetworking/Models/Request.swift, Sources/UtilityBeltNetworking/Protocols/RequestAdapter.swift, Sources/UtilityBeltNetworking/Protocols/RequestInterceptor.swift, Sources/UtilityBeltNetworking/Protocols/RequestRetrier.swift, Tests/UtilityBeltNetworkingTests/Tests/RequestInterceptorTests.swift, Tests/UtilityBeltNetworkingTests/Tests/RequestTests.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-3202
Adds the ability to retry a request if it failed or fails validation.
- Added the `RequestRetrier` protocol and updated `RequestInterceptor` to conform to it
- Call the `RequestRetrier` when a task completes and either fails or does not pass validation, which will allow for a new request to be attempted
- Handled TODO around cancelling/suspending tasks while the `RequestInterceptor` is being called to ensure the cancellation or suspension request is upheld after returning from those async methods
- Moved existing `RequestAdapter` tests into a new test file named `RequestTests` and use a `Request` object directly instead of going through the `HTTPClient`
- Added new tests centered around retrying requests
=> IOS-3202: Feature/Retrying Requests

Sources/UtilityBeltNetworking/Models/Request.swift, Tests/UtilityBeltNetworkingTests/Tests/RequestTests.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-3202
Added the ability to check if a `Request` is "running", which will mean that the request is being adapted prior to being sent to the server, is actively communicating with the server, or is asking the `RequestRetrier` if a retry should be conducted.
=> IOS-3202: Feature/Add ability to determine if a Request is "running"

.github/workflows/ci.yml
Updating our GitHub Actions YAML to use Xcode 13 and iOS/tvOS 15. 
- I removed the `DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer` line as I was getting errors about that directory not existing
- Changed ` macos-latest` to `macos-11` as "latest" was not using Big Sur
- Added a line in each workflow to manually switch to the new version of Xcode using `xcode-select` (When searching for how to set the Xcode version in Github Actions YAML, not much documentation exists and I can't find anything on the `DEVELOPER_DIR` environment variable, but I've seen other repos using the `xcode-select` method and it seems a bit more straightforward
=> Update to Xcode 13, iOS 15

Package.swift
Bumps the iOS target from iOS 10 to 11 due to the following issue (noted in the Xcode 13 release notes):
> Swift libraries depending on Combine may fail to build for targets including armv7 and i386 architectures. (82183186, 82189214)
Workaround: Use an updated version of the library that isn’t impacted (if available) or remove armv7 and i386 support (for example, increase the deployment target of the library to iOS 11 or higher).
Additionally, from the [Apple Developer Forums:](https://developer.apple.com/forums/thread/682285)
> Generally speaking for the Xcode 13 RC, there are known issues specific to apps using libraries with a deployment target that still supports 32-bit iOS versions (iOS 10 or before), even if the app target only supports 64-bit iOS versions (iOS 11 …
=> Feature/Bump iOS target to iOS 11

Sources/UtilityBeltNetworking/Models/Request.swift, Sources/UtilityBeltNetworking/Protocols/RequestRetrier.swift, Tests/UtilityBeltNetworkingTests/Tests/RequestTests.swift
**Issue Link**
https://spothero.atlassian.net/browse/IOS-3809
In order to capture difference between errors resulting in the same HTTP Status Code, we need access to the HTTP Response Data to parse it into our internal error object.
This PR adds the response data (if available) in the arguments of `RequestRetrier`.
=> Added Data in RequestRetrier.retry
